HOST = yangyangfu
PROJECT_NAME = energyplus



# ARGUMENTS
ENERGYPLUS_VERSION=22.2.0  
ENERGYPLUS_SHA=c249759bad 
ENERGYPLUS_INSTALL_VERSION=22-2-0 
ENERGYPLUS_TAG=v22.2.0
UBUNTU_BASE=22.04


build:
	docker build --no-cache --rm -t \
	$(HOST)/$(PROJECT_NAME):$(ENERGYPLUS_TAG) \
	--build-arg ENERGYPLUS_VERSION=$(ENERGYPLUS_VERSION) \
	--build-arg ENERGYPLUS_SHA=$(ENERGYPLUS_SHA) \
	--build-arg ENERGYPLUS_INSTALL_VERSION=$(ENERGYPLUS_INSTALL_VERSION) \
	--build-arg ENERGYPLUS_TAG=$(ENERGYPLUS_TAG) \
	--build-arg UBUNTU_BASE=$(UBUNTU_BASE) \
	.